//*******************************************************
// Copyright (c) MLRS project
// GPL3
// https://www.gnu.org/licenses/gpl-3.0.de.html
// OlliW @ www.olliw.eu
//*******************************************************
// hal
//*********************************************************
//-------------------------------------------------------
// DIY hardware browsing https://github.com/Hifly-rc/mlrs-elrs-Compatible-hardware
//-------------------------------------------------------
//#define DEVICE_NAME_SE77RX10
//#define DEVICE_NAME_SE77TX10
//#define DEVICE_NAME_SE22RX21
//#define DEVICE_NAME_SE28TX12
//#define DEVICE_NAME_SE19RX10
//#define DEVICE_NAME_SE220RX12
//#define DEVICE_NAME_SE28TX21
//#define DEVICE_NAME_SE32TX21
//#define MLRS_FEATURE_OLED
//#define DEVICE_HAS_DIVERSITY
#define DEVICE_NAME_XLITE_SE28TX22

#ifdef DEBUG_ENABLED
#undef DEBUG_ENABLED
#endif

//-- MLRS Hifly device
//-- RX
//#define MLRS_FEATURE_915_MHZ_FCC
#ifdef RX_HIFLY_WLE5CC
#undef SETUP_RF_BAND
#undef SETUP_MODE
//-- redefine config tx parameter
#undef SETUP_RX_SERIAL_BAUDRATE
#define SETUP_RX_SERIAL_BAUDRATE 3 // 3=57600
#undef SETUP_RX_CHANNEL_ORDER
#define SETUP_RX_CHANNEL_ORDER 0 // AETR

#ifdef DEVICE_NAME_SE77RX10
#define DEVICE_NAME "HIFLY-SE77RX1.0"
#define DEVICE_IS_RECEIVER
#define DEVICE_HAS_SX126x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_MODE MODE_31HZ
#endif
#endif

#ifdef RX_HIFLY_F103CB
#undef SETUP_RF_BAND
#undef SETUP_MODE
//-- redefine config tx parameter
#undef SETUP_RX_SERIAL_BAUDRATE
#define SETUP_RX_SERIAL_BAUDRATE 3 // 3=57600
#undef SETUP_RX_CHANNEL_ORDER
#define SETUP_RX_CHANNEL_ORDER 0 // AETR

#ifdef DEVICE_NAME_SE19RX10
#define DEVICE_NAME "HIFLY-SE19RX1.0"
#define DEVICE_IS_RECEIVER
#define DEVICE_HAS_SX127x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_MODE MODE_19HZ
#endif
#ifdef DEVICE_NAME_SE28RX12
#define DEVICE_NAME "HIFLY-SE28RX1.2"
#define DEVICE_IS_RECEIVER
#define DEVICE_HAS_SX128x
#define FREQUENCY_BAND_2P4_GHZ
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_2P4_GHZ
#define SETUP_MODE MODE_50HZ
#endif
#ifdef DEVICE_NAME_SE22RX12
#define DEVICE_NAME "HIFLY-SE22RX1.2"
#define DEVICE_IS_RECEIVER
#define DEVICE_HAS_SX126x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_MODE MODE_31HZ
#endif
#ifdef DEVICE_NAME_SE220RX12
#define DEVICE_NAME "HIFLY-SE22RX1.2"
#define DEVICE_IS_RECEIVER
#define DEVICE_HAS_SX126x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SX_USE_CRYSTALOSCILLATOR
#define SETUP_MODE MODE_31HZ
#endif
#ifdef DEVICE_NAME_SE28RX21
#define DEVICE_NAME "HIFLY-SE28RX2.1"
#define DEVICE_IS_RECEIVER
#define DEVICE_HAS_SX128x
#define FREQUENCY_BAND_2P4_GHZ
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_2P4_GHZ
#define SETUP_MODE MODE_50HZ
#endif
#ifdef DEVICE_NAME_DE28RX21
#define DEVICE_HAS_DIVERSITY
#define DEVICE_NAME "HIFLY-DE28RX2.1"
#define DEVICE_IS_RECEIVER
#define DEVICE_HAS_SX128x
#define FREQUENCY_BAND_2P4_GHZ
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_2P4_GHZ
#define SETUP_MODE MODE_50HZ
#endif
#ifdef DEVICE_NAME_SE22RX21
#define DEVICE_NAME "HIFLY-SE22RX2.1"
#define DEVICE_IS_RECEIVER
#define DEVICE_HAS_SX126x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_MODE MODE_31HZ
#endif
#ifdef DEVICE_NAME_SE220RX21
#define DEVICE_NAME "HIFLY-SE220RX2.1"
#define DEVICE_IS_RECEIVER
#define DEVICE_HAS_SX126x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SX_USE_CRYSTALOSCILLATOR
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_MODE MODE_31HZ
#endif
#ifdef DEVICE_NAME_SE32RX21
#define DEVICE_NAME "HIFLY-SE32RX2.1"
#define DEVICE_IS_RECEIVER
#define DEVICE_HAS_SX127x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_MODE MODE_19HZ
#endif
#endif

//-- TX
#ifdef TX_HIFLY_WLE5CC
#undef SETUP_RF_BAND
#undef SETUP_MODE
//-- redefine config tx parameter
#undef SETUP_TX_SERIAL_BAUDRATE
#define SETUP_TX_SERIAL_BAUDRATE 3 // 3=57600
#undef SETUP_TX_CHANNEL_ORDER
#define SETUP_TX_CHANNEL_ORDER 0 // AETR

#ifdef MLRS_FEATURE_OLED
#define DEVICE_HAS_I2C_DISPLAY_ROT180
#endif
#ifdef DEVICE_NAME_SE77TX10
#define DEVICE_NAME "HIFLY-SE77TX1.0"
#define DEVICE_IS_TRANSMITTER
#define DEVICE_HAS_SX126x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_MODE MODE_31HZ
#endif
#endif

#ifdef TX_HIFLY_F072CB
#undef SETUP_RF_BAND
#undef SETUP_MODE
//-- redefine config tx parameter
#undef SETUP_TX_SERIAL_BAUDRATE
#define SETUP_TX_SERIAL_BAUDRATE 3 // 3=57600
#undef SETUP_TX_CHANNEL_ORDER
#define SETUP_TX_CHANNEL_ORDER 0 // AETR

#ifdef MLRS_FEATURE_OLED
#define DEVICE_HAS_I2C_DISPLAY_ROT180
#endif
#ifdef DEVICE_NAME_SE22TX22
#ifdef  HSE_VALUE
#undef HSE_VALUE
#define HSE_VALUE 12000000U
#endif
#define DEVICE_NAME "HIFLY-SE22TX2.2"
#define DEVICE_IS_TRANSMITTER
#define DEVICE_HAS_SX126x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_MODE MODE_31HZ
#endif
#endif

#ifdef TX_HIFLY_F103CB
#undef SETUP_RF_BAND
#undef SETUP_MODE
//-- redefine config tx parameter
#undef SETUP_TX_SERIAL_BAUDRATE
#define SETUP_TX_SERIAL_BAUDRATE 3 // 3=57600
#undef SETUP_TX_CHANNEL_ORDER
#define SETUP_TX_CHANNEL_ORDER 0 // AETR

#ifdef MLRS_FEATURE_OLED
#define DEVICE_HAS_I2C_DISPLAY_ROT180
#endif

#ifdef DEVICE_NAME_SE28TX12
#define DEVICE_NAME "HIFLY-SE28TX1.2"
#define DEVICE_IS_TRANSMITTER
#define DEVICE_HAS_SX128x
#define FREQUENCY_BAND_2P4_GHZ
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_2P4_GHZ
#define SETUP_MODE MODE_50HZ
#endif
#ifdef DEVICE_NAME_SE28TX12S
#define DEVICE_HAS_SBUS
#define DEVICE_NAME "HIFLY-SE28TX1.2S"
#define DEVICE_IS_TRANSMITTER
#define DEVICE_HAS_SX128x
#define FREQUENCY_BAND_2P4_GHZ
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_2P4_GHZ
#define SETUP_MODE MODE_50HZ
#endif
#ifdef DEVICE_NAME_SE220TX12
#define DEVICE_NAME "HIFLY-SE220TX1.2"
#define DEVICE_IS_TRANSMITTER
#define DEVICE_HAS_SX126x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SX_USE_CRYSTALOSCILLATOR
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_MODE MODE_31HZ
#endif
#ifdef DEVICE_NAME_SE220TX12S
#define DEVICE_HAS_SBUS
#define DEVICE_NAME "HIFLY-SE220TX1.2S"
#define DEVICE_IS_TRANSMITTER
#define DEVICE_HAS_SX126x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SX_USE_CRYSTALOSCILLATOR
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_MODE MODE_31HZ
#endif
#ifdef DEVICE_NAME_SE28TX20
#define DEVICE_NAME "HIFLY-SE28TX2.0"
#define DEVICE_IS_TRANSMITTER
#define DEVICE_HAS_SX128x
#define FREQUENCY_BAND_2P4_GHZ
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_2P4_GHZ
#define SETUP_MODE MODE_50HZ
#endif
#ifdef DEVICE_NAME_SE22TX20
#define DEVICE_NAME "HIFLY-SE22TX2.0"
#define DEVICE_IS_TRANSMITTER
#define DEVICE_HAS_SX126x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_MODE MODE_31HZ
#endif
#ifdef DEVICE_NAME_SE220TX20
#define DEVICE_NAME "HIFLY-SE220TX2.0"
#define DEVICE_IS_TRANSMITTER
#define DEVICE_HAS_SX126x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SX_USE_CRYSTALOSCILLATOR
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_MODE MODE_31HZ
#endif

#ifdef DEVICE_NAME_SE28TX21
#define DEVICE_NAME "HIFLY-SE28TX2.1"
#define DEVICE_IS_TRANSMITTER
#define DEVICE_HAS_SX128x
#define FREQUENCY_BAND_2P4_GHZ
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_2P4_GHZ
#define SETUP_MODE MODE_50HZ
#endif
#ifdef DEVICE_NAME_DE28TX21
#define DEVICE_HAS_DIVERSITY
#define DEVICE_NAME "HIFLY-DE28TX2.1"
#define DEVICE_IS_TRANSMITTER
#define DEVICE_HAS_SX128x
#define FREQUENCY_BAND_2P4_GHZ
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_2P4_GHZ
#define SETUP_MODE MODE_50HZ
#endif
#ifdef DEVICE_NAME_SE22TX21
#define DEVICE_NAME "HIFLY-SE22TX2.1"
#define DEVICE_IS_TRANSMITTER
#define DEVICE_HAS_SX126x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_MODE MODE_31HZ
#endif
#ifdef DEVICE_NAME_SE220TX21
#define DEVICE_NAME "HIFLY-SE220TX2.1"
#define DEVICE_IS_TRANSMITTER
#define DEVICE_HAS_SX126x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SX_USE_CRYSTALOSCILLATOR
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_MODE MODE_31HZ
#endif
#ifdef DEVICE_NAME_SE32TX21
#define DEVICE_NAME "HIFLY-SE32TX2.1"
#define DEVICE_IS_TRANSMITTER
#define DEVICE_HAS_SX127x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_MODE MODE_19HZ
#endif
#ifdef DEVICE_NAME_SE22TX22
#define DEVICE_NAME "HIFLY-SE22TX2.2"
#define DEVICE_IS_TRANSMITTER
#define DEVICE_HAS_SX126x
#define FREQUENCY_BAND_868_MHZ
#define FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_915_MHZ_FCC
#define SETUP_MODE MODE_31HZ
#endif
#ifdef DEVICE_NAME_XLITE_SE28TX22
#define DEVICE_NAME "XLITE-SE28TX2.2"
#define DEVICE_IS_TRANSMITTER
#define DEVICE_HAS_SX128x
#define FREQUENCY_BAND_2P4_GHZ
#define SETUP_RF_BAND SETUP_FREQUENCY_BAND_2P4_GHZ
#define SETUP_MODE MODE_50HZ
#endif
#endif
